server.port=8080

spring.datasource.url=jdbc:postgresql://ecommerce-db.cmrm6oggi5qh.us-east-1.rds.amazonaws.com:5432/ecommerdb
spring.datasource.username=postgres
spring.datasource.password=Sanket123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

jwt.secret=ChangeThisToALongRandomSecretKeyForJWTSigningAtLeast256Bits
jwt.expiration=86400000
